### ISSUE TITLE
/ma not working

### ISSUE THREAD

**Issue by Latravant** [Selindrile/Repeater#1]
anyone know what i'm doing wrong? i'm using the repeater add on. it works fine when i cast a tier 1 spell, but when i use  /ma "fire ii"  <t> or fire 2 etc. i get an error message form playonline 
(>>/ma "fire ii" <t>)
(... a command error occured)

**Comment by Selindrile** [comment]
//repeater command input /ma "Fire II" <t>

Should work, but it's possible handling of quotes isn't working correctly, may I recommend using the Shortcuts addon, then you can just use:

//repeater command fire2

**Comment by Latravant** [comment]
ok i'll try that thank you

**Comment by Latravant** [comment]
works! tyvm
